"""empty message

Revision ID: 776a48846de8
Revises: 959e310542ab
Create Date: 2016-10-29 13:34:54.158406

"""

# revision identifiers, used by Alembic.
revision = '776a48846de8'
down_revision = '959e310542ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
